name: Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
    - run: |
        python3 setup.py .
        pip install pytest
        pytest
