name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install mypy pytest
        pip install -e .
    - name: Run mypy
      run: |
        mypy --ignore-missing-imports bronzebeard
    - name: Run pytest
      run: |
        pytest
